import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.JOptionPane;

public class AddNewEmployee_jFrame extends javax.swing.JFrame {
    
    private MyHashTable mainHT;

    /**
     * Creates new form AddNewEmployee_jFrame
     */
    public AddNewEmployee_jFrame() {
        initComponents();
        FTEIntFrame.setVisible(false);
        PTEIntFrame.setVisible(false);
        pack();
        
        successFlag.setVisible(false);        
    }
    
    public void setMainHT (MyHashTable theRefVal) {
        mainHT = theRefVal;
        System.out.println("ADD EMPLOYEE LIVE");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FTERadButt = new javax.swing.JRadioButton();
        PTERadButt = new javax.swing.JRadioButton();
        empNumTxt = new javax.swing.JTextField();
        firstNameTxt = new javax.swing.JTextField();
        lastNameTxt = new javax.swing.JTextField();
        genderTxt = new javax.swing.JTextField();
        locationTxt = new javax.swing.JTextField();
        deductRateTxt = new javax.swing.JTextField();
        exitButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        FTEIntFrame = new javax.swing.JInternalFrame();
        salaryTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        PTEIntFrame = new javax.swing.JInternalFrame();
        hourlyWageTxt = new javax.swing.JTextField();
        hoursPerWeekTxt = new javax.swing.JTextField();
        weeksPerYearTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        successFlag = new javax.swing.JInternalFrame();
        successTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FTERadButt.setText("Full Time Employee");
        FTERadButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTERadButtActionPerformed(evt);
            }
        });
        getContentPane().add(FTERadButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 367, -1, -1));

        PTERadButt.setText("Part Time Employee");
        PTERadButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PTERadButtActionPerformed(evt);
            }
        });
        getContentPane().add(PTERadButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 367, -1, -1));
        getContentPane().add(empNumTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 105, 426, -1));
        getContentPane().add(firstNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 145, 426, -1));
        getContentPane().add(lastNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 185, 426, -1));
        getContentPane().add(genderTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 225, 426, -1));
        getContentPane().add(locationTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 265, 426, -1));
        getContentPane().add(deductRateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 305, 426, -1));

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 652, -1, -1));

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 652, -1, -1));

        FTEIntFrame.setVisible(true);

        jLabel9.setText("Salary ($)");

        javax.swing.GroupLayout FTEIntFrameLayout = new javax.swing.GroupLayout(FTEIntFrame.getContentPane());
        FTEIntFrame.getContentPane().setLayout(FTEIntFrameLayout);
        FTEIntFrameLayout.setHorizontalGroup(
            FTEIntFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salaryTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
            .addGroup(FTEIntFrameLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        FTEIntFrameLayout.setVerticalGroup(
            FTEIntFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FTEIntFrameLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(24, 24, 24)
                .addComponent(salaryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        getContentPane().add(FTEIntFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 405, 230, 269));

        PTEIntFrame.setVisible(true);

        jLabel10.setText("Hourly Wage ($):");

        jLabel11.setText("Hours Per Week");

        jLabel12.setText("Weeks Per Year");

        javax.swing.GroupLayout PTEIntFrameLayout = new javax.swing.GroupLayout(PTEIntFrame.getContentPane());
        PTEIntFrame.getContentPane().setLayout(PTEIntFrameLayout);
        PTEIntFrameLayout.setHorizontalGroup(
            PTEIntFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hourlyWageTxt)
            .addComponent(hoursPerWeekTxt)
            .addComponent(weeksPerYearTxt)
            .addGroup(PTEIntFrameLayout.createSequentialGroup()
                .addGroup(PTEIntFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(0, 129, Short.MAX_VALUE))
        );
        PTEIntFrameLayout.setVerticalGroup(
            PTEIntFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTEIntFrameLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(24, 24, 24)
                .addComponent(hourlyWageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(hoursPerWeekTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(weeksPerYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(PTEIntFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 405, 230, -1));

        jLabel1.setText("Fill Employee Info Below:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 68, 155, 19));

        jLabel2.setText("Select:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 339, 47, -1));

        jLabel3.setText("Employee Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 108, -1, -1));

        jLabel4.setText("First Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 148, -1, -1));

        jLabel5.setText("Last Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 188, -1, -1));

        jLabel6.setText("Gender (M:1, F:2, O:3)");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 228, -1, -1));

        jLabel7.setText("Location (TO: 1, MI:2)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 268, -1, -1));

        jLabel8.setText("Deduct Rate (0-0.99)");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 308, -1, -1));

        jLabel13.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 24)); // NOI18N
        jLabel13.setText("Add Employee Menu");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        successFlag.setVisible(true);

        successTxt.setForeground(new java.awt.Color(0, 204, 0));
        successTxt.setText("Employee Added Sucessfully!");

        javax.swing.GroupLayout successFlagLayout = new javax.swing.GroupLayout(successFlag.getContentPane());
        successFlag.getContentPane().setLayout(successFlagLayout);
        successFlagLayout.setHorizontalGroup(
            successFlagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(successFlagLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(successTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );
        successFlagLayout.setVerticalGroup(
            successFlagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(successFlagLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(successTxt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(successFlag, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 180, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void scheduleFlagRemoval(javax.swing.JInternalFrame flag){
        int duration = 3000;
        Timer timer = new Timer (duration, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                flag.setVisible(false);
            }
        });
        
        timer.setRepeats(false);
        timer.start();
    }
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void FTERadButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTERadButtActionPerformed
        FTEIntFrame.setVisible(true);
        PTEIntFrame.setVisible(false);
    }//GEN-LAST:event_FTERadButtActionPerformed

    private void PTERadButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PTERadButtActionPerformed
        PTEIntFrame.setVisible(true);
        FTEIntFrame.setVisible(false);
    }//GEN-LAST:event_PTERadButtActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
    try {
        int theEmpNum = Integer.parseInt(empNumTxt.getText());
        String theFirstName = firstNameTxt.getText();
        String theLastName = lastNameTxt.getText();
        
        int theGender = Integer.parseInt(genderTxt.getText());
        
        // validate gender range
        if (theGender <= 0 || theGender > 3){
            throw new IllegalArgumentException("Gender option is not in range;");
        }
        
        int theWorkLoc = Integer.parseInt(locationTxt.getText());
        
        // validate work location range
        if (theWorkLoc <= 0 || theWorkLoc > 2) {
            throw new IllegalArgumentException("Work location option is not in range.");
        }
    
        
        String strDR = deductRateTxt.getText();
        double dDeductRate = Double.parseDouble(strDR);
        
        // validate the deduct rate
        if (dDeductRate < 0 || dDeductRate > 0.99){
            throw new IllegalArgumentException("Deduct rate must be between 0 and 0.99.");
        }
        
        // FULL TIME EMPLOYEE HANDLING
        
        if (FTERadButt.isSelected()){
            String strSalary = salaryTxt.getText();
            double dSalary = Double.parseDouble(strSalary);
            
            // Validate Salary Range
            if (dSalary <= 0) {
                throw new IllegalArgumentException("Salary must be greater than zero.");
            }
            
            FTE theFTE = new FTE(theEmpNum, theFirstName, theLastName, theGender, theWorkLoc, dDeductRate, dSalary);
           
            if (mainHT.addEmployee(theFTE)){
                successFlag.setVisible(true);
                scheduleFlagRemoval(successFlag);
                JOptionPane.showMessageDialog(null, "Click to Add a New Employee");
            } else {
                throw new IllegalArgumentException("Employee with the same number already exists in system!");
            }
        }
        
        // PART TIME EMPLOYEE HANDLING 
        if (PTERadButt.isSelected()){
            String strHourlyWage = hourlyWageTxt.getText();
            double theHourlyWage = Double.parseDouble (strHourlyWage);
            
            // Validate Wage range
            if (theHourlyWage <= 0) {
                throw new IllegalArgumentException("Hourly wage must be greater than zero.");
            }
            
            String strHoursPerWeek = hoursPerWeekTxt.getText();
            double theHoursPerWeek = Double.parseDouble(strHoursPerWeek);
            
            // Validate Hours Per Week Range
            if (theHoursPerWeek <= 0 || theHoursPerWeek > 168) {
                throw new IllegalArgumentException("Hours per week must be between 1 and 168.");
            }
            
            String strWeeksPerYear = weeksPerYearTxt.getText();
            double theWeeksPerYear = Double.parseDouble(strWeeksPerYear);
            
            // Validate Weeks per Year Range
            if (theWeeksPerYear <= 0 || theWeeksPerYear > 52 ) {
                throw new IllegalArgumentException ("Weeks per year must be between 1 and 52.");
            }
            
            PTE thePTE = new PTE (theEmpNum, theFirstName, theLastName, theGender, theWorkLoc,dDeductRate, theHourlyWage, theHoursPerWeek, theWeeksPerYear);
            
            if (mainHT.addEmployee(thePTE)){
                successFlag.setVisible(true);
                scheduleFlagRemoval(successFlag);
                JOptionPane.showMessageDialog(null, "Click to Add a New Employee");
            } else {
                throw new IllegalArgumentException("Employee with the same number already exists in the system!");
            }
        }
        
        // reset the text fields
        empNumTxt.setText("");
        firstNameTxt.setText("");
        lastNameTxt.setText("");
        genderTxt.setText("");
        locationTxt.setText("");
        deductRateTxt.setText("");
        salaryTxt.setText("");
        hourlyWageTxt.setText("");
        hoursPerWeekTxt.setText("");
        weeksPerYearTxt.setText("");
    } catch (NumberFormatException e) {
        // Handle invalid number format in input fields
        JOptionPane.showMessageDialog(null, "Invalid number format. Please enter valid numeric values.");
    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
        
    }//GEN-LAST:event_addButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewEmployee_jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewEmployee_jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewEmployee_jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewEmployee_jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewEmployee_jFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame FTEIntFrame;
    private javax.swing.JRadioButton FTERadButt;
    private javax.swing.JInternalFrame PTEIntFrame;
    private javax.swing.JRadioButton PTERadButt;
    private javax.swing.JButton addButton;
    private javax.swing.JTextField deductRateTxt;
    private javax.swing.JTextField empNumTxt;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField firstNameTxt;
    private javax.swing.JTextField genderTxt;
    private javax.swing.JTextField hourlyWageTxt;
    private javax.swing.JTextField hoursPerWeekTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNameTxt;
    private javax.swing.JTextField locationTxt;
    private javax.swing.JTextField salaryTxt;
    private javax.swing.JInternalFrame successFlag;
    private javax.swing.JLabel successTxt;
    private javax.swing.JTextField weeksPerYearTxt;
    // End of variables declaration//GEN-END:variables
}
