import javax.swing.JOptionPane;
import javax.swing.table.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class EmployeeSearchFrame extends javax.swing.JFrame {
    // ATTRIBUTES
    
    private MyHashTable mainHT;
    private DefaultTableModel model;
    
    /**
     * Creates new form EmployeeSearchFrame
     */
    public EmployeeSearchFrame() {
        initComponents();
    }
    
    public void setMainHT(MyHashTable theRefVal){
        mainHT = theRefVal;
        System.out.println("EMPLOYEE SEARCH IS LIVE");
        
        model = new DefaultTableModel (new Object[] {"Status", "Emp Num", "First Name", "Last Name", "Gender", "Location", "Deduct Rate", "Net Income $", "Salary $","Wage $","Hrs/Wk","Wks/Year"},1);
            dispTable.setModel(model);
            dispTable.setAutoCreateColumnsFromModel(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        empNumField = new javax.swing.JTextField();
        searchButton = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        empSelStatus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dispTable = new javax.swing.JTable();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 24)); // NOI18N
        jLabel1.setText("Employee Search Menu");

        jLabel2.setText("Get info on an Employee by entering in their Employee Number:");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Employee Selected:");

        empSelStatus.setText("No Employee Currently Selected");

        dispTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(dispTable);

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(empSelStatus)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(26, 26, 26)
                                .addComponent(empNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchButton)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 378, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(exitButton)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(360, 360, 360))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(empNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(empSelStatus))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(exitButton)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
try {
    int theEmpNum = Integer.parseInt(empNumField.getText());
    
    // Call the getEmployee method to search for the employee
    EmployeeInfo foundEmployee = mainHT.getEmployee(theEmpNum);
    
    if (foundEmployee != null) {
        empSelStatus.setVisible(false);
        
        if (foundEmployee instanceof FTE) {
            FTE theFTE = (FTE) foundEmployee;
            
            model.setValueAt("Full Time",0, 0);
            model.setValueAt(foundEmployee.empNum, 0, 1);
            model.setValueAt(foundEmployee.firstName,0,2);
            model.setValueAt(foundEmployee.lastName,0,3);
            model.setValueAt(foundEmployee.gender,0,4);
            model.setValueAt(foundEmployee.workLoc,0,5);
            model.setValueAt(foundEmployee.deductRate,0, 6);
            model.setValueAt(foundEmployee.calcNetAnnualIncome(),0, 7);
            model.setValueAt(((FTE) foundEmployee).yearlySalary,0, 8);
            model.setValueAt("N/A",0,9);
            model.setValueAt("N/A",0,10);
            model.setValueAt("N/A",0,11);  
        }
        if (foundEmployee instanceof PTE) {
            PTE thePTE = (PTE) foundEmployee;
            
            model.setValueAt("Part Time",0, 0);
            model.setValueAt(foundEmployee.empNum, 0, 1);
            model.setValueAt(foundEmployee.firstName,0,2);
            model.setValueAt(foundEmployee.lastName,0,3);
            model.setValueAt(foundEmployee.gender,0,4);
            model.setValueAt(foundEmployee.workLoc,0,5);
            model.setValueAt(foundEmployee.deductRate,0, 6);
            model.setValueAt(foundEmployee.calcNetAnnualIncome(),0, 7);
            model.setValueAt("N/A",0, 8);
            model.setValueAt(((PTE) foundEmployee).hourlyWage,0,9);
            model.setValueAt(((PTE) foundEmployee).hoursPerWeek,0,10);
            model.setValueAt(((PTE) foundEmployee).weeksPerYear,0,11); 
        }
    } else {
            model.setValueAt("", 0, 0);
            model.setValueAt("", 0, 1);
            model.setValueAt("", 0, 2);
            model.setValueAt("", 0, 3);
            model.setValueAt("", 0, 4);
            model.setValueAt("", 0, 5);
            model.setValueAt("", 0, 6);
            model.setValueAt("", 0, 7);
            model.setValueAt("", 0, 8);
            model.setValueAt("", 0, 9);
            model.setValueAt("", 0, 10);
            model.setValueAt("", 0, 11);
            
            empSelStatus.setVisible(true);
            throw new IllegalArgumentException("Employee not found.");
    }
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Invalid number format. Please enter valid numeric values.");
    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
}
    }//GEN-LAST:event_searchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeSearchFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable dispTable;
    private javax.swing.JTextField empNumField;
    private javax.swing.JLabel empSelStatus;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton searchButton;
    // End of variables declaration//GEN-END:variables
}
